### ISSUE TITLE
Game ends but does not feel like [Enhancement]

### ISSUE THREAD

**Issue by TheDoctorOne** [koridesu/React-tic-tac-toe#2]
Related to issue #1 .
After game ends, fields feel like clickable even though they are not.

Steps to reproduce:
  1. Start the Game
  2. Play the game so one side wins
  3. See "Winner" Text
  4. Hover on an empty field

**Comment by koridesu** [comment]
Yeah it was intentionally not removed because of just players feels the click effects and animations for more long time. Maybe I have been little bit ignore it (￢‿￢ )
If it seems weird please let me now so fix it quickly!
